# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-22 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0006_auto_20161022_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбоми'},
        ),
    ]
