# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0007_auto_20161022_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_in_album', to='image_hosting.Album'),
        ),
    ]
