# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0008_auto_20161022_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='album',
            name='private_policy',
            field=models.CharField(choices=[('PRT', 'Private'), ('PBC', 'Public'), ('ULS', 'Unlisted')], max_length=3, verbose_name='Тип'),
        ),
    ]
