# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0009_auto_20161026_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='private_policy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Unlisted', 'Unlisted')], max_length=3, verbose_name='Тип'),
        ),
    ]
