# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-22 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0011_auto_20161118_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'permissions': (('album_owner', 'Album owner'),), 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбоми'},
        ),
    ]
