# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-04 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0012_auto_20161122_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 12, 4, 19, 21, 58, 359355, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
