# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_hosting', '0013_album_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_hosting.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=35, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='album',
            name='private_policy',
            field=models.CharField(choices=[(b'Private', b'Private'), (b'Public', b'Public'), (b'Unlisted', b'Unlisted')], max_length=8, verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf'),
        ),
    ]
