# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0015_auto_20161225_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-upload_date',), 'verbose_name': 'Зображення', 'verbose_name_plural': 'Зображення'},
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='album',
            name='private_policy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Unlisted', 'Unlisted')], max_length=8, verbose_name='Тип'),
        ),
    ]
