# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('upload_date', models.DateTimeField(default=datetime.datetime)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
