# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0002_remove_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Зображення', 'verbose_name_plural': 'Зображення'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='/media'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
