# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0003_auto_20161013_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
