# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_hosting', '0004_auto_20161018_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
